### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [joao-pinheiro/atx_psu#1]
Hello!

I found this project from https://hackaday.com/2022/12/08/a-very-tidy-atx-bench-psu/

Could you please add information about the license of this repository — is it allowed to copy, change and use design files and images in any purpose?
It would be great to see any popular open source license.

**Comment by joao-pinheiro** [comment]
Hi Vazhnov, thank you for your interest in the project!
As requested, I've added licensing information to the repository (MIT License)

**Comment by vazhnov** [comment]
MIT license — amazing! Thank you!
